# Generated by Django 5.1.5 on 2025-02-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.PositiveBigIntegerField(auto_created=True, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('mobile', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.PositiveBigIntegerField()),
                ('father', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=38)),
                ('balance', models.PositiveIntegerField(default=500)),
                ('pin', models.ImageField(blank=True, upload_to='')),
                ('photo', models.ImageField(upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=7)),
            ],
        ),
    ]
