# Generated by Django 5.1.5 on 2025-02-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STATE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender'),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.state'),
        ),
    ]
