# Generated by Django 5.1.5 on 2025-02-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_state_remove_account_address_alter_account_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
    ]
